### ISSUE TITLE
Nexus bug

### ISSUE THREAD

**Issue by BadTomas** [xHyroM/NexusBlock#4]
Hi i found a bug.

Budu psat cesky je to jednodusi.

Ked block sa vytezi a je z neho bedrock tak normalne sa vrati spet po dobe. Ale jak nahle je v bedrocku a dá sa RESTART tak po restarttu se vynuluje na 0 ale furt je bedrock a nechce se vratit musim rucne

**Comment by ScrollDP** [comment]
Tento problém môžem potvrdiť

**Comment by xHyroM** [comment]
Dobre, opravím. Pravdepodobne check s Material Bedrock pri štarte nejde, tak sa na to pozriem.

**Comment by xHyroM** [comment]
Problém by mal byť opravený v dev verzii, https://github.com/xHyroM/NexusBlock/tree/main/out/artifacts/nexusblock_bukkit_jar
