### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by Zarkness** [xHyroM/NexusBlock#7]
add support to mysql, support to put to each nexus block a condition to be able to break, for example to be able to break the block x times a day and every x hours, that you need to fulfill certain conditions like kill 20 zombies, get 64 rottenflesh, have x level of experience, have x island level (here it would be nice to add support for different skyblock plugins like bentobox, superiorskyblock2 and iridiumskyblock), be able to break it only at certain time of the day, have voted for the server x times, need a permission, have x item either a normal minecraft item or a custom item.

**Comment by xHyroM** [comment]
Thanks for ideas
